### ISSUE TITLE
Make "sign in" text consistent

### ISSUE THREAD

**Issue by brendangadd** [StatCan/StatCan.OrchardCore#15]
Variations of "sign in" are used across the portal and could use alignment.

* Hamburger menu (mobile): "Sign In"
* Homepage button: "Login"
* Sign in page: "Log In"

Seems like services tend to use "sign in" these days. GitHub uses "sign up", "sign in", "signed in". But as long as its consistent...

**Comment by bbronzan** [comment]
Text is all synced up now!

We'll be going with "Log in" because it's the term used by Orchard, so I don't want the titles to say "Sign in" and the URLs say "/login".

I don't mind "Sign in", but both terms are pretty widely used. We considered changing the URL to "/signin/ but compatibility is unknown, so we're going to play it safe.

**Comment by bbronzan** [comment]
> Text is all synced up now!
> 
> We'll be going with "Log in" because it's the term used by Orchard, so I don't want the titles to say "Sign in" and the URLs say "/login".
> 
> I don't mind "Sign in", but both terms are pretty widely used. We considered changing the URL to "/signin/ but compatibility is unknown, so we're going to play it safe.

Done!
