### ISSUE TITLE
Improve language toggle text in menu

### ISSUE THREAD

**Issue by brendangadd** [StatCan/StatCan.OrchardCore#17]
When the language toggle button is collapsed into a hamburger menu, its displayed in the menu as a lowercase abbreviation (e.g. "fr"). It should probably read "Français" in this state, which would cohere better with the "Sign In" option below it.

**Comment by bbronzan** [comment]
Good find, thanks!

The text was updated to EN and FR to be consistent with the desktop view.

"English" and "Francais" are alternative options, but we'll stick with the abbreviations to keep the minimal design style.

Fixed by MA in https://github.com/StatCan/StatCan.OrchardCore/commit/1320f0b82bb186a1582efd538761e6a809534bfc
