### ISSUE TITLE
Dead end for new users at the home page. 

### ISSUE THREAD

**Issue by sasha-force** [StatCan/StatCan.OrchardCore#25]
When a new user comes to this page https://portal.covid.cloud.statcan.ca/ there are no links or instructions on how to get an account if they don't have one already. 

This leaves users at a dead-end - they need either a sign up link or instructions on what to do next.

**Comment by M-A-Boucher** [comment]
Hi @sasha-force, the AAW portal uses Azure OIDC for sign in. Clicking the **Log in** button, brings first time users to the Azure SSO page. Clicking the **Log in** simply signs them in. There is no sign up per se. The users of this portal must already have an Azure account. If you think the **Log in** button is confusing to new users, we can for sure explore the idea of putting instructions on the homepage.

Having a **Sign up** button could cause more confusion because it would just lead the user through the same flow as the **Log in** button. And would lead users to believe they can sign up to something that they can't really sign up to.

**Comment by sasha-force** [comment]
Hi @m-a-boucher. I think this might be easier to discuss in real time - will book something in Outlook.

Cheers,

Sasha

Sasha Force
(she/elle)

UX Research Team Lead, IT Project Delivery
Statistics Canada / Government of Canada
sasha.force@canada.ca

Chef d’équipe de XU – Livraison de projets TI
Statistique Canada / Gouvernement du Canada
sasha.force@canada.ca

________________________________

**Comment by bbronzan** [comment]
The register/sign-up dead-end was intentional for a few reasons actually:

- There is no "REGISTER" or "SIGN UP" action on the current AAW because users were not able to sign up for it on their own. For the hackathon, users were onboarded outside the AAW and then provided the URL to log in afterwards.
- We told explicitly to disable that feature because they were onboarding users and they were using Azure only.
- There is a LOG IN button as a primary call-to-action for users who were on-boarded already. Once logged in, the content is available. 
- If users are now able to register/sign up for the AAW, we can enable the manual registration feature and the updates to the experience to support it.

**Comment by bbronzan** [comment]
Brought this up during the P22 stand-up today, and it was clarified with us that users will be allowed to  "sign up" and use the AAW. 

We'll enable the registration feature and update the experience to reflect this. 

Since users will need a Cloud account to use the AAW, we'll work in some content to highlight this and provide users a way to get more info/get the ball rolling to create a Cloud account if they don't have one already.

Once we have something to look at, we'll reach out. How does that sound?

**Comment by nelucas72** [comment]
Per @brendangadd Simply add messaging indicating that sign in requires an azure cloud account and the portal isn't generally available to all.

**Comment by sasha-force** [comment]
The key is this: anyone coming to that page needs to know what their next steps are, whatever they are, even if their next step is to wait until the platform is more widely available.

If they have to wait, they need to know how they'll know when it's available. Signing up for notification would be ideal - someone has come to the page because they're interested. The last thing we want to do is alienate people who have demonstrated an interest.

**Comment by M-A-Boucher** [comment]
We’re still in the process of finding an SMTP server for such an occasion. There are a lot of things that we can’t do right now (such as email notifications) because of time/resource constraints. Rest assured that most of what you propose will come when we have all the necessary pieces.

**Comment by sasha-force** [comment]
Fantastic thank you!
________________________________

**Comment by bbronzan** [comment]
Yeah as @M-A-Boucher said, we have a whole email confirmation experience already designed and mapped out, but we don't have the SMTP server. 

As I mentioned on Slack, this will likely make it into the next sprint so we'll have some more to look at later this week.
