### ISSUE TITLE
UX: Highlight Kubeflow and Minio as the key elements

### ISSUE THREAD

**Issue by blairdrummond** [StatCan/StatCan.OrchardCore#42]
The UX feedback I'm getting is that users are overwhelmed by the number of options in the portal. I think Kubeflow and Minio are the two most important options for 90% of users, so maybe there's a way to highlight "Get started with these two" and then leave the rest below?

**Comment by bbronzan** [comment]
Hey @blairdrummond sorry I just saw this now! I know it's not part of this current sprint, but I wanted to chime in since I noticed it.

I see what you're saying, so perhaps for the time being we could update the 3 "hot links" at the top:

Current: Kubeflow, R-Shiny, GitHub
Proposed: Kubeflow, MinIO, R-Shiny

This would elevate MinIO slightly. We're also going to add a star next to the items on the portal that are also featured in the "hot links" at the top. 

These "hot links" buttons at the top function as a set of featured tools, which is similar to the "Get started" idea you're proposing but not exactly the same. 

Let's start with this and see how it works out. We'll also discuss internally the idea of a more prominent "Featured/Get started" section.

What do you think?

**Comment by blairdrummond** [comment]
Yep I think that's great!

**Comment by bbronzan** [comment]
Ok great! Mino has been promoted to the hot links, and GitHub got the boot. (sorry not sorry GitHub)

The star was added too, which will come in the next deployment. It was a super tiny thing to add.

Thanks again for the feedback.
